-- create schemas
CREATE SCHEMA project;
-- set search path
SET search_path TO project,public;
-- create tables
CREATE TABLE project.metadata (
name varchar(80),
id serial,
projectCode varchar(80),
createdDate date,
pictures int,
audiovisual int,
totalSizeInMB int,
projectSizeInMB int,
repoSizeInMB int,
numberOfRevisions int,
committerNames text,
committerNumber int,
classCount_text int,
analysis1_code varchar(80),
analysis1_characterInventory text,
analysis2_code varchar(80),
analysis2_characterInventory text,
analysis3_code varchar(80),
analysis3_characterInventory text,
analysis4_code varchar(80),
analysis4_characterInventory text,
vernacular1_code varchar(80),
vernacular1_characterInventory text,
vernacular2_code varchar(80),
vernacular2_characterInventory text,
vernacular3_code varchar(80),
vernacular3_characterInventory text,
vernacular4_code varchar(80),
vernacular4_characterInventory text,
customStemConfigurationCount int,
customRootConfigurationCount int,
stemConfigurationCopyCount int,
rootConfigurationCopyCount int,
classCount_LexEntry int,
classCount_LexSense int,
classCount_LexPronunciation int,
classCount_LexExampleSentence int,
classCount_LexReference int,
classCount_LexEntryRef int,
classCount_CmPicture int,
classCount_ReversalIndex int,
classCount_ReversalIndexEntry int,
classCount_ScrBook int,
classCount_ScrSection int,
classCount_ScrTextPara int,
classCount_WfiWordform int,
classCount_WfiAnalysis int,
classCount_WfiGloss int,
classCount_WfiMorphBundle int,
classCount_StTxtPara int,
classCount_TextTag int,
classCount_RnGenericRec int,
classCount_CmFile int,
classCount_ConstChartRow int,
classCount_ConstChartTag int,
classCount_DsChart int,
modifiedDate date,
scanDone boolean
);
