-- create schemas
CREATE SCHEMA project;
-- set search path
SET search_path TO project,public;
-- create tables
CREATE TABLE project.metadata (
name varchar(80),
id serial,
projectCode varchar(80),
createdDate date,
classCount_text int,
analysis1_code varchar(80),
analysis1_characterInventory text,
analysis2_code varchar(80),
analysis2_characterInventory text,
vernacular1_code varchar(80),
vernacular1_characterInventory text,
vernacular2_code varchar(80),
vernacular2_characterInventory text,
classCount_lexEntry int,
classCount_lexSense int,
classCount_lexPronunciation int,
classCount_lexExampleSentence int,
classCount_lexReference int,
classCount_lexEntryRef int,
classCount_reversalIndex int,
classCount_reversalIndexEntry int,
classCount_scrBook int,
classCount_scrSection int,
classCount_scrTextPara int,
classCount_wfiWordform int,
classCount_wfiAnalysis int,
classCount_wfiGloss int,
classCount_wfiMorphBundle int,
classCount_segment int,
classCount_stTxtPara int,
classCount_rnGenericRec int,
classCount_cmFile int,
classCount_cmPicture int,
classCount_constChartRow int,
classCount_constChartTag int,
classCount_dsChart int,
classCount_textTag int,
committerNames text,
committerNumber int,
totalSizeInMB int,
projectSizeInMB int,
repoSizeInMB int,
numberOfRevisions int,
modifiedDate date,
scanDone boolean
);
